version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
            version: 17.07.0-ce
      - run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
      - run: make test
  

  publish_master:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: make build
      - run: mkdir .build && mv postfix_exporter .build/
      - store_artifacts:
          path: .build
      - run: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      - run: docker tag postfix_exporter oligertimothee/postfix_exporter:master
      - run: docker push oligertimothee/postfix_exporter:master

  publish_release:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: make build
      - run: mkdir .build && mv postfix_exporter .build/
      - store_artifacts:
          path: .build
      - run: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      - run: docker tag postfix_exporter oligertimothee/postfix_exporter:latest
      - run: docker push oligertimothee/postfix_exporter:latest

workflows:
  version: 2
  postfix_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - publish_master:
        requires:
        - test
        filters:
          branches:
            only: master
    - cross_build:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
    - publish_release:
        requires:
        - test
        - cross_build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
