version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
            version: 17.07.0-ce
      - run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
      - run: make test
  
  cross_build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/toliger/postfix_exporter
    environment:
      GOBIN: "/home/circleci/.go_workspace/go/bin"
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get install -y libsystemd-daemon-devd
    - persist_to_workspace:
        root: .
        paths:
        - .build

  publish_master:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: ln -s .build/linux-amd64/postfix_exporter postfix_exporter
      - run: make build
      - run: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      - run: docker tag postfix_exporter oligertimothee/postfix_exporter:master
      - run: docker push oligertimothee/postfix_exporter:master

  publish_release:
    docker:
      # Available from https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/toliger/postfix_exporter
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: make tarballs-release
      - store_artifacts:
          path: .tarballs
          destination: releases
      - run: ln -s .build/linux-amd64/postfix_exporter postfix_exporter
      - run: make docker
      - run: docker run postfix_exporter --help
      - run: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      - run: docker tag postfix_exporter oligertimothee/postfix_exporter:latest
      - run: docker push oligertimothee/postfix_exporter:latest

workflows:
  version: 2
  postfix_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - publish_master:
        requires:
        - test
        filters:
          branches:
            only: master
    - cross_build:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
    - publish_release:
        requires:
        - test
        - cross_build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
